### ISSUE TITLE
A little help to use AWS-SDK with google app script

### ISSUE THREAD

**Issue by Thomas3795** [dxdc/aws-sdk-google-apps#13]
Hi,

I found your component aws-sdk-google-apps on github and it's awesome !
Thanks a lot for this job !

I added it as a library on my google script, but I don't know how to use it in my script.

I just need to use it to send emails with SES API, but I haven't found on Internet how to do that in a google app script.

With the AWS Stack, I'm a newby and I really don't know how to use it from google app script, how to put my credentials, and to call the SES function to send emails.

If you know all this stuff, I would be very grateful if you can send me some examples.

Thank you so much
Thomas

**Comment by Thomas3795** [comment]
Thanks a lot for your quick answer, but I can't see where I put my AWS SES Credentials
Do you have a step by step tutorial ?

**Comment by dxdc** [comment]
```
const AWS_CONFIG = {
  accessKey: 'AK0ZXZD0KGNG4KG6REBP', // use your own AWS key
  secretKey: 'EXrPgHC41HEW2YownLUnJLgh6bMsrmW1uva1ic24', // use your own AWS key
  region: 'us-east-1',
};
```

Please see the README on the homepage. AWS is very complicated, and learning how to use it is out of the scope of this project.
