### ISSUE TITLE
Script ID cannot find any library

### ISSUE THREAD

**Issue by jfilowk** [dxdc/aws-sdk-google-apps#8]
Hello,

The ScriptID in the README does not find any result when you try to import the library.

![image](https://user-images.githubusercontent.com/4893898/181157560-a1844cf5-536d-4bb9-8a8f-28f647cf9313.png)

Has it changed?

**Comment by dxdc** [comment]
@jfilowk thanks for the alert! please try again, I think the permissions weren't updated to share.

**Comment by jfilowk** [comment]
Still the same error. It cannot find any library.

In the project options, do you have the same ID?

**Comment by dxdc** [comment]
I've corrected the ScriptId and permissions, please see if it works for you now: `1J6iN9mJE-NK6LGTlZcngsflJEx59tE3ZOW4-2cdHbgw0So2MmEcRZxKG`

**Comment by jfilowk** [comment]
It works!
![image](https://user-images.githubusercontent.com/4893898/181160918-c67fba85-61fe-4a20-b172-2060f5e73ccd.png)

Thanks!
