### ISSUE TITLE
Adding EC2

### ISSUE THREAD

**Issue by AbdealiJK** [dxdc/aws-sdk-google-apps#9]
Came across your repo after some searching and I tried `AWSLIB.AWS.EC2` but it looks like EC2 is not available in the standard library

It looks like onyl a few services are aded by default.
In your library - maybe it would be more flexible to add all the services ?

**Comment by dxdc** [comment]
Yes, all the services are not there by default.

See the README:

> Working examples for Simple Email Service (SES), S3, and Lambda. This project can easily accommodate _all_ other AWS services, e.g.,

```
npm run sdk --sdk=ses,s3,ec2,lambda,dynamodb && npm run build
```

Adding every possible AWS service slows down the library significantly. Roughly speaking, the final library size is 15x larger with all services added, and the majority of those services are unlikely to be used.

If you add 1-2 sample/common methods for popular services like EC2 (see: [S3 method](https://github.com/dxdc/aws-sdk-google-apps/blob/master/dist/S3.js) as an example) and submit a PR, I will consider adding that service to the defaults.

**Comment by AbdealiJK** [comment]
Thanks, I was able to follow the instructions and get it working in my own project.

Also raised a PR: https://github.com/dxdc/aws-sdk-google-apps/pull/10
If you would like to add it to your existing AWS library

Awesome work with the patching of browser specific things :+1:
